services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=gogospacedevuser
      - POSTGRES_PASSWORD=gogospacedevuser
      - POSTGRES_DB=gogospace_dev
    ports:
      - "5432:5432"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://gogospacedevuser:gogospacedevuser@postgres:5432/gogospace_dev?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]