// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: url.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createURL = `-- name: CreateURL :one
INSERT INTO url (
  id, url
) VALUES (
  $1, $2
) RETURNING id, url, created_at
`

type CreateURLParams struct {
	ID  uuid.UUID `json:"id"`
	URL string    `json:"url"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (URL, error) {
	row := q.db.QueryRowContext(ctx, createURL, arg.ID, arg.URL)
	var i URL
	err := row.Scan(&i.ID, &i.URL, &i.CreatedAt)
	return i, err
}
